{{- if and .Values.cleanuperr.enabled (not .Values.cleanuperr.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cleanuperr-secret
  labels:
    app.kubernetes.io/name: cleanuperr
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
    {{- if not (or (eq (.Values.cleanuperr.env.DOWNLOAD_CLIENT | toString) "none") (eq (.Values.cleanuperr.env.DOWNLOAD_CLIENT | toString) "disabled")) }}
    QBITTORRENT__USERNAME: {{ .Values.cleanuperr.secrets.qbittorrent.username | b64enc }}
    QBITTORRENT__PASSWORD: {{ .Values.cleanuperr.secrets.qbittorrent.password | b64enc }}
    {{- end }}
    {{- if eq (.Values.cleanuperr.env.SONARR__ENABLED | toString) "true" }}
    SONARR__INSTANCES__0__APIKEY: {{ .Values.cleanuperr.secrets.sonarr.apiKey | b64enc }}
    {{- end }}
    {{- if eq (.Values.cleanuperr.env.RADARR__ENABLED | toString) "true" }}
    RADARR__INSTANCES__0__APIKEY: {{ .Values.cleanuperr.secrets.radarr.apiKey | b64enc }}
    {{- end }}
    {{- if eq (.Values.cleanuperr.env.LIDARR__ENABLED | toString) "true" }}
    LIDARR__INSTANCES__0__APIKEY: {{ .Values.cleanuperr.secrets.lidarr.apiKey | b64enc }}
    {{- end }}
{{- end }}
