name: searxng
maintainers:
  - name: kubitodev
    url: https://kubito.dev
apiVersion: v2
appVersion: 1.0.1
version: 1.0.7
description: Kubito SearXNG Helm Chart
home: https://github.com/kubitodev/helm/tree/main/charts/searxng
icon: https://kubito.dev/images/kubito.svg
keywords:
  - kubernetes
  - searxng
  - metasearch
  - search
  - privacy
sources:
  - https://github.com/searxng/searxng
