{{- $replicas := .Values.replicaCount -}}
{{- if .Values.podDisruptionBudget.enabled }}
{{- if le ($replicas | int) 1 }}
{{- fail "podDisruptionBudget.minAvailable must be larger than 1 when replicaCount is 1" -}}
{{- end -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
{{- end }}
